version: 0.2
  
phases:
  install:
    runtime-versions:
        java: corretto11
  pre_build:
    commands:
      - chmod 777 scripts/detectchanges_and_build.sh
  build:
    commands:
      - ./scripts/detectchanges_and_build.sh
      